version: "3"
services:
  db:
    image: postgres:14.0
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin