server:
  address: localhost
  port: 80
  servlet:
    context-path: /ggxxreload

spring:
  liquibase:
    enabled: true
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres?charSet=UTF8&currentSchema=ggxx'
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: none
logging:
  level:
    web: INFO

schedule:
  afk-players:
    delay: 180
    frequency: 30
  ping-players:
    frequency: 200
    timeout: 5000


deactivate:
  time:
    delay: 180
    schedule: 30